# This file is automatically generated from traits.build
# package, via the file remake.yml.whisker:
# edit the file there (or the files that it includes).

# Load R resources
library(traits.build)

# Load data resources
schema <- get_schema()
resource_metadata <- get_schema("config/metadata.yml", "metadata")
definitions <- get_schema("config/traits.yml", "traits")
unit_conversions <- get_unit_conversions("config/unit_conversions.csv")
taxon_list <- read_csv_char("config/taxon_list.csv")

# Build each source
Lp_Arkh1996_config <- dataset_configure("data/Lp_Arkh1996/metadata.yml", definitions)
Lp_Arkh1996_raw <- traits.build::dataset_process("data/Lp_Arkh1996/data.csv", Lp_Arkh1996_config, schema, resource_metadata, unit_conversions)
Lp_Arkh1996 <- dataset_update_taxonomy(Lp_Arkh1996_raw, taxon_list)

Lp_checkthisone_config <- dataset_configure("data/Lp_checkthisone/metadata.yml", definitions)
Lp_checkthisone_raw <- traits.build::dataset_process("data/Lp_checkthisone/data.csv", Lp_checkthisone_config, schema, resource_metadata, unit_conversions)
Lp_checkthisone <- dataset_update_taxonomy(Lp_checkthisone_raw, taxon_list)

Lp_CoulHesp2009_config <- dataset_configure("data/Lp_CoulHesp2009/metadata.yml", definitions)
Lp_CoulHesp2009_raw <- traits.build::dataset_process("data/Lp_CoulHesp2009/data.csv", Lp_CoulHesp2009_config, schema, resource_metadata, unit_conversions)
Lp_CoulHesp2009 <- dataset_update_taxonomy(Lp_CoulHesp2009_raw, taxon_list)

Lp_DrecMonr2018_config <- dataset_configure("data/Lp_DrecMonr2018/metadata.yml", definitions)
Lp_DrecMonr2018_raw <- traits.build::dataset_process("data/Lp_DrecMonr2018/data.csv", Lp_DrecMonr2018_config, schema, resource_metadata, unit_conversions)
Lp_DrecMonr2018 <- dataset_update_taxonomy(Lp_DrecMonr2018_raw, taxon_list)

Lp_Emme2008_config <- dataset_configure("data/Lp_Emme2008/metadata.yml", definitions)
Lp_Emme2008_raw <- traits.build::dataset_process("data/Lp_Emme2008/data.csv", Lp_Emme2008_config, schema, resource_metadata, unit_conversions)
Lp_Emme2008 <- dataset_update_taxonomy(Lp_Emme2008_raw, taxon_list)

Lp_fishbase_10_config <- dataset_configure("data/Lp_fishbase_10/metadata.yml", definitions)
Lp_fishbase_10_raw <- traits.build::dataset_process("data/Lp_fishbase_10/data.csv", Lp_fishbase_10_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_10 <- dataset_update_taxonomy(Lp_fishbase_10_raw, taxon_list)

Lp_fishbase_11_config <- dataset_configure("data/Lp_fishbase_11/metadata.yml", definitions)
Lp_fishbase_11_raw <- traits.build::dataset_process("data/Lp_fishbase_11/data.csv", Lp_fishbase_11_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_11 <- dataset_update_taxonomy(Lp_fishbase_11_raw, taxon_list)

Lp_fishbase_12_config <- dataset_configure("data/Lp_fishbase_12/metadata.yml", definitions)
Lp_fishbase_12_raw <- traits.build::dataset_process("data/Lp_fishbase_12/data.csv", Lp_fishbase_12_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_12 <- dataset_update_taxonomy(Lp_fishbase_12_raw, taxon_list)

Lp_fishbase_13_config <- dataset_configure("data/Lp_fishbase_13/metadata.yml", definitions)
Lp_fishbase_13_raw <- traits.build::dataset_process("data/Lp_fishbase_13/data.csv", Lp_fishbase_13_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_13 <- dataset_update_taxonomy(Lp_fishbase_13_raw, taxon_list)

Lp_fishbase_2_config <- dataset_configure("data/Lp_fishbase_2/metadata.yml", definitions)
Lp_fishbase_2_raw <- traits.build::dataset_process("data/Lp_fishbase_2/data.csv", Lp_fishbase_2_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_2 <- dataset_update_taxonomy(Lp_fishbase_2_raw, taxon_list)

Lp_fishbase_3_config <- dataset_configure("data/Lp_fishbase_3/metadata.yml", definitions)
Lp_fishbase_3_raw <- traits.build::dataset_process("data/Lp_fishbase_3/data.csv", Lp_fishbase_3_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_3 <- dataset_update_taxonomy(Lp_fishbase_3_raw, taxon_list)

Lp_fishbase_4_config <- dataset_configure("data/Lp_fishbase_4/metadata.yml", definitions)
Lp_fishbase_4_raw <- traits.build::dataset_process("data/Lp_fishbase_4/data.csv", Lp_fishbase_4_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_4 <- dataset_update_taxonomy(Lp_fishbase_4_raw, taxon_list)

Lp_fishbase_5_config <- dataset_configure("data/Lp_fishbase_5/metadata.yml", definitions)
Lp_fishbase_5_raw <- traits.build::dataset_process("data/Lp_fishbase_5/data.csv", Lp_fishbase_5_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_5 <- dataset_update_taxonomy(Lp_fishbase_5_raw, taxon_list)

Lp_fishbase_6_config <- dataset_configure("data/Lp_fishbase_6/metadata.yml", definitions)
Lp_fishbase_6_raw <- traits.build::dataset_process("data/Lp_fishbase_6/data.csv", Lp_fishbase_6_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_6 <- dataset_update_taxonomy(Lp_fishbase_6_raw, taxon_list)

Lp_fishbase_7_config <- dataset_configure("data/Lp_fishbase_7/metadata.yml", definitions)
Lp_fishbase_7_raw <- traits.build::dataset_process("data/Lp_fishbase_7/data.csv", Lp_fishbase_7_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_7 <- dataset_update_taxonomy(Lp_fishbase_7_raw, taxon_list)

Lp_fishbase_8_config <- dataset_configure("data/Lp_fishbase_8/metadata.yml", definitions)
Lp_fishbase_8_raw <- traits.build::dataset_process("data/Lp_fishbase_8/data.csv", Lp_fishbase_8_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_8 <- dataset_update_taxonomy(Lp_fishbase_8_raw, taxon_list)

Lp_fishbase_9_config <- dataset_configure("data/Lp_fishbase_9/metadata.yml", definitions)
Lp_fishbase_9_raw <- traits.build::dataset_process("data/Lp_fishbase_9/data.csv", Lp_fishbase_9_config, schema, resource_metadata, unit_conversions)
Lp_fishbase_9 <- dataset_update_taxonomy(Lp_fishbase_9_raw, taxon_list)

Lp_Jeff2003_config <- dataset_configure("data/Lp_Jeff2003/metadata.yml", definitions)
Lp_Jeff2003_raw <- traits.build::dataset_process("data/Lp_Jeff2003/data.csv", Lp_Jeff2003_config, schema, resource_metadata, unit_conversions)
Lp_Jeff2003 <- dataset_update_taxonomy(Lp_Jeff2003_raw, taxon_list)

Lp_John1987_config <- dataset_configure("data/Lp_John1987/metadata.yml", definitions)
Lp_John1987_raw <- traits.build::dataset_process("data/Lp_John1987/data.csv", Lp_John1987_config, schema, resource_metadata, unit_conversions)
Lp_John1987 <- dataset_update_taxonomy(Lp_John1987_raw, taxon_list)

Lp_Kava2000_config <- dataset_configure("data/Lp_Kava2000/metadata.yml", definitions)
Lp_Kava2000_raw <- traits.build::dataset_process("data/Lp_Kava2000/data.csv", Lp_Kava2000_config, schema, resource_metadata, unit_conversions)
Lp_Kava2000 <- dataset_update_taxonomy(Lp_Kava2000_raw, taxon_list)

Lp_Kenc1977_config <- dataset_configure("data/Lp_Kenc1977/metadata.yml", definitions)
Lp_Kenc1977_raw <- traits.build::dataset_process("data/Lp_Kenc1977/data.csv", Lp_Kenc1977_config, schema, resource_metadata, unit_conversions)
Lp_Kenc1977 <- dataset_update_taxonomy(Lp_Kenc1977_raw, taxon_list)

Lp_LawSado2018_config <- dataset_configure("data/Lp_LawSado2018/metadata.yml", definitions)
Lp_LawSado2018_raw <- traits.build::dataset_process("data/Lp_LawSado2018/data.csv", Lp_LawSado2018_config, schema, resource_metadata, unit_conversions)
Lp_LawSado2018 <- dataset_update_taxonomy(Lp_LawSado2018_raw, taxon_list)

Lp_Pard1993_config <- dataset_configure("data/Lp_Pard1993/metadata.yml", definitions)
Lp_Pard1993_raw <- traits.build::dataset_process("data/Lp_Pard1993/data.csv", Lp_Pard1993_config, schema, resource_metadata, unit_conversions)
Lp_Pard1993 <- dataset_update_taxonomy(Lp_Pard1993_raw, taxon_list)

Lp_SudhSham2009_config <- dataset_configure("data/Lp_SudhSham2009/metadata.yml", definitions)
Lp_SudhSham2009_raw <- traits.build::dataset_process("data/Lp_SudhSham2009/data.csv", Lp_SudhSham2009_config, schema, resource_metadata, unit_conversions)
Lp_SudhSham2009 <- dataset_update_taxonomy(Lp_SudhSham2009_raw, taxon_list)

Lp_Vijv1980_config <- dataset_configure("data/Lp_Vijv1980/metadata.yml", definitions)
Lp_Vijv1980_raw <- traits.build::dataset_process("data/Lp_Vijv1980/data.csv", Lp_Vijv1980_config, schema, resource_metadata, unit_conversions)
Lp_Vijv1980 <- dataset_update_taxonomy(Lp_Vijv1980_raw, taxon_list)

Lp_WangLau2020_config <- dataset_configure("data/Lp_WangLau2020/metadata.yml", definitions)
Lp_WangLau2020_raw <- traits.build::dataset_process("data/Lp_WangLau2020/data.csv", Lp_WangLau2020_config, schema, resource_metadata, unit_conversions)
Lp_WangLau2020 <- dataset_update_taxonomy(Lp_WangLau2020_raw, taxon_list)

Lp_WillNonn2018_config <- dataset_configure("data/Lp_WillNonn2018/metadata.yml", definitions)
Lp_WillNonn2018_raw <- traits.build::dataset_process("data/Lp_WillNonn2018/data.csv", Lp_WillNonn2018_config, schema, resource_metadata, unit_conversions)
Lp_WillNonn2018 <- dataset_update_taxonomy(Lp_WillNonn2018_raw, taxon_list)

Lp_YounMang1994_config <- dataset_configure("data/Lp_YounMang1994/metadata.yml", definitions)
Lp_YounMang1994_raw <- traits.build::dataset_process("data/Lp_YounMang1994/data.csv", Lp_YounMang1994_config, schema, resource_metadata, unit_conversions)
Lp_YounMang1994 <- dataset_update_taxonomy(Lp_YounMang1994_raw, taxon_list)


traits.build_database_raw <- austraits::bind_databases(
  Lp_Arkh1996,
  Lp_CoulHesp2009,
  Lp_DrecMonr2018,
  Lp_Emme2008,
  Lp_fishbase_10,
  Lp_fishbase_11,
  Lp_fishbase_12,
  Lp_fishbase_13,
  Lp_fishbase_2,
  Lp_fishbase_3,
  Lp_fishbase_4,
  Lp_fishbase_5,
  Lp_fishbase_6,
  Lp_fishbase_7,
  Lp_fishbase_8,
  Lp_fishbase_9,
  Lp_Jeff2003,
  Lp_John1987,
  Lp_Kava2000,
  Lp_Kenc1977,
  Lp_LawSado2018,
  Lp_Pard1993,
  Lp_SudhSham2009,
  Lp_Vijv1980,
  Lp_WangLau2020,
  Lp_WillNonn2018,
  Lp_YounMang1994,
  NULL)

# Version information
version_number <- util_get_version("config/metadata.yml")
git_SHA <- util_get_SHA()

# Combine all the source into one resource
traits.build_database <- build_add_version(traits.build_database_raw, version_number, git_SHA)

# Save to file
dir.create("export/data/curr", FALSE, TRUE)
saveRDS(traits.build_database, "export/data/curr/traits.build_database.rds")
a=traits.build_database$traits
